### ISSUE TITLE
`Ember.String.singularize`, `Ember.String.pluralize`

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-rfc176-data#33]
These are actually injected by `ember-inflector`. The correct imports are:

```
import {singularize, pluralize} from 'ember-inflector';
```

How do we deal with this and `@ember/string`?

related: https://github.com/ember-cli/ember-rfc176-data/issues/12#issuecomment-313913683

**Comment by rwjblue** [comment]
Not sure what you mean? It seems like this repo is properly handling this already?

[emberjs/rfcs#176](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) did not contain references to either `Ember.String.pluralize` or `Ember.String.singularize` (since the are not public API's provided by Ember). Neither [old-shims.json](https://github.com/ember-cli/ember-rfc176-data/blob/master/old-shims.json) or [globals.json](https://github.com/ember-cli/ember-rfc176-data/blob/master/globals.json) provide any information for `pluralize` / `singularize`.

**Comment by rwjblue** [comment]
The ember-modules-codemod also has explicit tests ([input](https://github.com/ember-cli/ember-modules-codemod/blob/master/__testfixtures__/leave-unmatched-destructuring.input.js) and [output](https://github.com/ember-cli/ember-modules-codemod/blob/master/__testfixtures__/leave-unmatched-destructuring.output.js) added in https://github.com/ember-cli/ember-modules-codemod/pull/24) to ensure that `Ember.String.pluralize` is _not_ converted to new modules.

**Comment by locks** [comment]
Right, but I'm wondering what's the right approach here because `ember-data` comes by default with a new project, which then includes the inflector and these methods.
*/me deprecates all the things*

**Comment by Turbo87** [comment]
I agree with @rwjblue, this seems unrelated to the purpose of this repo
